"""Markdown report writer."""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from models import BusinessRecord, UnassignedBucket

_ENC_ORDER = ["wpa3", "wpa2", "wpa", "wep", "open"]


def write_report(
    businesses: dict[str, BusinessRecord],
    unassigned: UnassignedBucket,
    total_events: int,
    output_dir: Path,
) -> Path:
    now = datetime.now(timezone.utc)
    filename = f"kkd-bi-{now.strftime('%Y-%m-%d-%H%M')}.md"
    out_path = output_dir / filename

    ranked = sorted(businesses.values(), key=lambda b: b.score, reverse=True)
    total_sessions = len({sid for rec in ranked for sid in rec.session_ids})

    lines: list[str] = [
        f"# KKD BI Report — {now.strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "Generated by Belt.works BI Processor (kkd-leaf Plugin B)  ",
        f"Sessions: {total_sessions} | Events: {total_events:,} | "
        f"Businesses: {len(ranked)}",
        "",
        "---",
        "",
    ]

    for rank, rec in enumerate(ranked, 1):
        lines += _business_section(rank, rec)

    lines += _unassigned_section(unassigned)

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out_path


# ── Section builders ──────────────────────────────────────────────────────────


def _business_section(rank: int, rec: BusinessRecord) -> list[str]:
    return [
        f"## {rank}. {rec.name} — Score: {rec.score}/100 ({rec.tier})",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Sessions | {len(rec.session_ids)} |",
        f"| APs | {len(rec.aps)} |",
        f"| Best encryption | {rec.best_encryption or '—'} |",
        f"| AP vendors | {_ap_vendors(rec)} |",
        f"| BLE devices | {_ble_summary(rec)} |",
        f"| Client probes | {len(rec.probe_ssids)} unique SSIDs |",
        f"| Probe SSIDs seen | {_probe_list(rec)} |",
        "",
        "<details><summary>Score breakdown</summary>",
        "",
        f"- Encryption posture:      {rec.score_enc}/40",
        f"- AP vendor tier:          {rec.score_vendor}/30",
        f"- BLE device types:        {rec.score_ble}/20",
        f"- Infrastructure density:  {rec.score_density}/10",
        "",
        "</details>",
        "",
        "---",
        "",
    ]


def _unassigned_section(unassigned: UnassignedBucket) -> list[str]:
    lines: list[str] = [
        "## Unassigned",
        "",
        f"Events: {unassigned.event_count:,} | "
        f"BLE devices: {len(unassigned.ble_devices)}",
        "",
    ]

    unmatched = sorted(s for s in unassigned.ssids if s)
    if unmatched:
        lines.append(
            "Unique SSIDs not matched to any business "
            "(consider adding to boundary file):"
        )
        lines.append("")
        for ssid in unmatched[:50]:
            lines.append(f"- `{ssid}`")
        if len(unmatched) > 50:
            lines.append(f"- … and {len(unmatched) - 50} more")
        lines.append("")

    if unassigned.ble_devices:
        lines += [
            "Unassigned BLE devices:",
            "",
            "| MAC | Vendor | Name | Mfr ID |",
            "|---|---|---|---|",
        ]
        items = list(unassigned.ble_devices.values())[:30]
        for ble in items:
            lines.append(
                f"| {ble.mac} | {ble.vendor or '—'} "
                f"| {ble.ble_name or '—'} | {ble.ble_mfr or '—'} |"
            )
        if len(unassigned.ble_devices) > 30:
            lines.append(f"| … | {len(unassigned.ble_devices) - 30} more | | |")

    return lines


# ── Field formatters ──────────────────────────────────────────────────────────


def _ap_vendors(rec: BusinessRecord) -> str:
    vendors = sorted({ap.vendor.split()[0] for ap in rec.aps.values() if ap.vendor})
    return ", ".join(vendors[:4]) or "unknown"


def _ble_summary(rec: BusinessRecord) -> str:
    if not rec.ble_devices:
        return "—"
    labels = sorted({
        b.ble_name or b.vendor or "unknown"
        for b in rec.ble_devices.values()
    })
    return ", ".join(labels[:3]) + ("…" if len(labels) > 3 else "")


def _probe_list(rec: BusinessRecord) -> str:
    ssids = sorted(rec.probe_ssids)
    if not ssids:
        return "—"
    return (
        ", ".join(f'"{s}"' for s in ssids[:10])
        + ("…" if len(ssids) > 10 else "")
    )
